export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUETS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIn_FAIL";
export const USER_LOGOUT_REQUEST = "USER_LOGIN_LOGOUT";
